- id: basement_motion
  alias: 'Basement - Motion'
  trigger:
    #- platform: state
    #  entity_id: binary_sensor.basement_motion
    #  from: 'off'
    #  to: 'on'
    - platform: numeric_state
      entity_id: sensor.basement_cam_motion
      above: 100
  action:
    - service: notify.telegram_bot
      data:
        title: Send an images
        message: There is Motion.
        data:
          photo:
            - url: http://192.168.1.70:8081/photo.jpg

- id: frontdoor_motion
  alias: 'Front Door - Motion'
  trigger:
    #- platform: state
    #  entity_id: binary_sensor.front_door_motion
    #  from: 'off'
    #  to: 'on'
    - platform: numeric_state
      entity_id: sensor.front_door_cam_motion
      above: 15
  action:
    - service: notify.telegram_bot
      data:
        title: Send an images
        message: There is Motion.
        data:
          photo:
            - url: http://192.168.1.71:8081/photo.jpg

- id: night_mode_ipcam
  alias: 'Enable Nightmode at Sunset'
  trigger:
    platform: sun
    event: sunset
    offset: "+00:55:00"
  action:
    service: homeassistant.turn_on
    entity_id: switch.back_yard_cam_night_vision, switch.front_door_cam_night_vision
    
- id: night_mode_off_ipcam
  alias: 'Disable Nightmode at Sunset'
  trigger:
    platform: sun
    event: sunrise
    offset: "-00:30:00"
  action:
    service: homeassistant.turn_off
    entity_id: switch.back_yard_cam_night_vision, switch.front_door_cam_night_vision


#Alarm Clock
- id: alarm_clock
  alias: 'WakeUp Light Bedroom'
  hide_entity: True
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.wakeup_start_time_lights.state }}'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.wakeup
        state: 'on'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.wakeup_weekends
            state: 'on'
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
  action:
    service: script.wakeup_bedroom      

    
####################################################
#                  Zone                            #
#              Notifications                       #
####################################################

####################################################
#             Adam Home After Dark                 #
####################################################
- id: adam_home_after_dark
  alias: Adams Home After Dark
  trigger:
    platform: mqtt
    topic: smartthings/Adam Youngblood's Android/presence
    payload: 'PRESENT'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.back_door
        state: 'off'
  action:
    - service: notify.telegram_bot
      data:
        message: "Adam is home"
    - service: light.turn_on
      entity_id: light.back_door
 
 
# ################################################################################
# - id: front_door_nighttime_motion_initial
  # alias: 'Front Porch - Nighttime Motion'
  # trigger:
    # - platform: state
      # entity_id: binary_sensor.ring_front_door_motion
      # from: 'off'
      # to: 'on'
  # condition:
    # condition: and
    # conditions:
    # - condition: state
      # entity_id: sun.sun
      # state: 'below_horizon'
    # - condition: state
      # entity_id: light.front_porch_lights
      # state: 'off'
  # action:
# # Transition to this profile, even if on
    # - service: light.turn_on
      # data:
        # entity_id: light.front_porch_lights
        # profile: energize
        # transition: 1
# ################################################################################