- id: basement_motion
  alias: 'Basement - Motion'
  trigger:
    #- platform: state
    #  entity_id: binary_sensor.basement_motion
    #  from: 'off'
    #  to: 'on'
    - platform: numeric_state
      entity_id: sensor.basement_cam_motion
      above: 100
  action:
    - service: notify.telegram_bot
      data:
        title: Send an images
        message: There is Motion.
        data:
          photo:
            - url: http://192.168.1.70:8081/photo.jpg

- id: frontdoor_motion
  alias: 'Front Door - Motion'
  trigger:
    #- platform: state
    #  entity_id: binary_sensor.front_door_motion
    #  from: 'off'
    #  to: 'on'
    - platform: numeric_state
      entity_id: sensor.front_door_cam_motion
      above: 15
  action:
    - service: notify.telegram_bot
      data:
        title: Send an images
        message: There is Motion.
        data:
          photo:
            - url: http://192.168.1.71:8081/photo.jpg

- id: night_mode_ipcam
  alias: 'Enable Nightmode at Sunset'
  trigger:
    platform: sun
    event: sunset
    offset: "+00:55:00"
  action:
    service: homeassistant.turn_on
    entity_id: switch.back_yard_cam_night_vision, switch.front_door_cam_night_vision
    
- id: night_mode_off_ipcam
  alias: 'Disable Nightmode at Sunset'
  trigger:
    platform: sun
    event: sunrise
    offset: "-00:30:00"
  action:
    service: homeassistant.turn_off
    entity_id: switch.back_yard_cam_night_vision, switch.front_door_cam_night_vision


#Alarm Clock
- id: alarm_clock
  alias: 'WakeUp Light Bedroom'
  hide_entity: True
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.wakeup_start_time_lights.state }}'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.wakeup
        state: 'on'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.wakeup_weekends
            state: 'on'
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
  action:
    service: script.wakeup_bedroom      

    
####################################################
#                  Zone                            #
#              Notifications                       #
####################################################

####################################################
#             Adam Home After Dark                 #
####################################################
- id: adam_home_after_dark
  alias: Adams Home After Dark
  trigger:
    platform: mqtt
    topic: smartthings/Adam Youngblood's Android/presence
    payload: 'PRESENT'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.back_door
        state: 'off'
  action:
    - service: notify.telegram_bot
      data:
        message: "Adam is home"
    - service: light.turn_on
      entity_id: light.back_door
 
 
####################################################
#                Appliance                         #
#                Automation                        # 
####################################################

####################################################
#                Dishwasher                        #
####################################################
 #Dishwasher logic
  # Dishwasher set running
- id: dishwasher_started
  alias: Set dishwasher active when power detected

  trigger:
    platform: numeric_state
    entity_id: sensor.dishwasher_watts
    above: 15

  condition:
    - condition: state
      entity_id: input_select.dishwasher_status
      state: 'Off'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Running

# Dishwasher set drying
- id: dishwasher_drying
  alias: Set dishwasher drying when power drops

  trigger:
    platform: numeric_state
    entity_id: sensor.dishwasher_watts
    above: 300
    for:
      minutes: 1

  condition:
    condition: state
    entity_id: input_select.dishwasher_status
    state: Running

  action:
    service: input_select.select_option
    data:
      entity_id: input_select.dishwasher_status
      option: Drying

# Dishwasher set off
- id: dishwasher_finished
  alias: Set dishwasher off

  trigger:
    platform: numeric_state
    entity_id: sensor.dishwasher_watts
    below: 5
    for:
      minutes: 5

  condition:
    condition: state
    entity_id: input_select.dishwasher_status
    state: Drying

  action:
    service: input_select.select_option
    data:
      entity_id: input_select.dishwasher_status
      option: 'Off'

# Dishwasher Alert when done
- id: dishwasher_send_note
  alias: Send alert when dishwasher is done

  trigger:
    platform: state
    entity_id: input_select.dishwasher_status
    to: 'Off'

  action:
    service: notify.telegram_bot
    data:
      message: 'The Dishwasher has finished and is ready to be emptied.'
      title: 'Dishwasher Finished'
####################################################
#                Dishwasher End                    #
####################################################

####################################################
#                    Washer                        #
####################################################
  #washer only
- id: washer_started
  alias: Set washer active when power detected

  trigger:
    platform: numeric_state
    entity_id: sensor.washer_watts
    below: 200
    above: 90

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.washer_status
        state: 'Off'
      - condition: state  
        entity_id: input_select.dryer_status
        state: 'Off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washer_status
        option: Filling
  #washer and dryer running
- id: washer_started_with_dryer
  alias: Set washer active when power detected with dryer running
  trigger:
    platform: numeric_state
    entity_id: sensor.washer_watts
    below: 280
    above: 267
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.washer_status
        state: 'Off'
      - condition: state  
        entity_id: input_select.dryer_status
        state: 'On'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washer_status
        option: Filling

        
#Washer set Washing with dryer OFF
- id: washer_washing
  alias: Set washer washing when power drops

  trigger:
    platform: numeric_state
    entity_id: sensor.washer_watts
    below: 240
    above: 40
    for:
      minutes: 3

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.washer_status
        state: Filling
      - condition: state
        entity_id: input_select.dryer_status
        state: "Off"

  action:
    service: input_select.select_option
    data:
      entity_id: input_select.washer_status
      option: Washing

      #Washer set Washing with dryer ON
- id: washer_washing_with_dryer
  alias: Set washer washing with dryer going when power drops

  trigger:
    platform: numeric_state
    entity_id: sensor.washer_watts
    below: 500
    above: 330
    for:
      minutes: 2

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.washer_status
        state: Filling
      - condition: state
        entity_id: input_select.dryer_status
        state: "On"

  action:
    service: input_select.select_option
    data:
      entity_id: input_select.washer_status
      option: Washing
      

# Washer set off with dryer OFF
- id: washer_finished
  alias: Set Washer off

  trigger:
    platform: numeric_state
    entity_id: sensor.washer_watts
    below: 10
    for:
      minutes: 5

  condition:
    condition: state
    entity_id: input_select.washer_status
    state: Washing

  action:
    service: input_select.select_option
    data:
      entity_id: input_select.washer_status
      option: 'Off'
# Washer set off when dryer ON
- id: washer_finished_when_dryer_on
  alias: Set Washer off when dryer on
  trigger:
    platform: numeric_state
    entity_id: sensor.washer_watts
    below: 280
    above: 240
    for:
      minutes: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.washer_status
        state: Washing
      - condition: state
        entity_id: input_select.dryer_status
        state: 'On'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.washer_status
      option: 'Off'

# Washer Alert when done
- id: washer_send_note
  alias: Send alert when washer is done

  trigger:
    platform: state
    entity_id: input_select.washer_status
    to: 'Off'

  action:
    service: notify.telegram_bot
    data:
      message: 'The washer has finished and is ready for the dryer.'
      title: 'Washer Finished'
  
  
  
####################################################
#                  Washer End                      #
####################################################

####################################################
#                    Dryer                        #
####################################################
 #Dryer Only  
- id: dryer_started
  alias: Set dryer active when power detected
  trigger:
    platform: numeric_state
    entity_id: sensor.washer_watts
    above: 375
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.dryer_status
        state: 'Off'
      - condition: state
        entity_id: input_select.washer_status
        state: 'Off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dryer_status
        option: 'On'
#Dryer Only with washer running already  
- id: dryer_started_with_washer
  alias: Set dryer active when power detected with washer running
  trigger:
    platform: numeric_state
    entity_id: sensor.washer_watts
    above: 650
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.dryer_status
        state: 'Off'
      - condition: state
        entity_id: input_select.washer_status
        state: 'On'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dryer_status
        option: 'On'
        
# Dryer set off
- id: dryer_finished
  alias: Set Dryer off

  trigger:
    platform: numeric_state
    entity_id: sensor.washer_watts
    below: 245
    for:
      minutes: 5

  condition:
    condition: state
    entity_id: input_select.dryer_status
    state: 'On'

  action:
    service: input_select.select_option
    data:
      entity_id: input_select.dryer_status
      option: 'Off'

# Dryer Alert when done
- id: dryer_send_note
  alias: Send alert when dryer is done

  trigger:
    platform: state
    entity_id: input_select.dryer_status
    to: 'Off'

  action:
    service: notify.telegram_bot
    data:
      message: 'The dryer has finished and is ready.'
      title: 'Dryer Finished'
  
  
  
####################################################
#                  Washer End                      #
####################################################
  
# ################################################################################
# - id: front_door_nighttime_motion_initial
  # alias: 'Front Porch - Nighttime Motion'
  # trigger:
    # - platform: state
      # entity_id: binary_sensor.ring_front_door_motion
      # from: 'off'
      # to: 'on'
  # condition:
    # condition: and
    # conditions:
    # - condition: state
      # entity_id: sun.sun
      # state: 'below_horizon'
    # - condition: state
      # entity_id: light.front_porch_lights
      # state: 'off'
  # action:
# # Transition to this profile, even if on
    # - service: light.turn_on
      # data:
        # entity_id: light.front_porch_lights
        # profile: energize
        # transition: 1
# ################################################################################