- platform: mqtt
  name: Honeywell Thermostat
  modes:
    - 'heat'
    - 'cool'
    - 'off'
  fan_modes:
    - 'on'
    - 'auto'
    - 'circulate'
  mode_command_topic: "smartthings/THERMOSTAT/thermostatMode"
  mode_state_topic: "smartthings/THERMOSTAT/thermostatMode"
  #temperature_command_topic: "smartthings/THERMOSTAT/heatingSetpoint"  #For Heat  // Uncomment in winter
  temperature_command_topic: "smartthings/THERMOSTAT/coolingSetpoint"  
  fan_mode_command_topic: "smartthings/THERMOSTAT/thermostatFanMode"
  fan_mode_state_topic: "smartthings/THERMOSTAT/thermostatFanMode"
  temperature_state_topic: "smartthings/THERMOSTAT/temperature"
