homeassistant:
  name: Home
  latitude: !secret latit 
  longitude: !secret longit 
  elevation: 584
  unit_system: imperial
  time_zone: America/Detroit
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config

# Enables the frontend
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /www/custom_ui/state-card-custom-ui-es5.html
  themes: !include_dir_named themes/

# Enables configuration UI
config:



logger:
  default: error
  logs:
    homeassistant.components: warn
    #homeassistant.components.camera: critical
    #homeassistant.components.sensor: debug
    homeassistant.components.automation: debug
    #homeassistant.components.telegram_bot: debug
    homeassistant.components.mqtt: warn


http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

updater:

discovery:
  ignore:
    - plex_mediaserver

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

hue:
  bridges:
    - host: !secret hue_bridge

wemo:
  static:
    - 192.168.1.75
    - 192.168.1.76

mqtt: !include mqtt.yaml
media_player: !include media_player.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
switch: !include switches.yaml
binary_sensor: !include binary.yaml
telegram_bot: !include telegram.yaml
notify: !include notify.yaml
#android_ip_webcam: !include ipwebcam.yaml
climate: !include climate.yaml
sensor: !include sensors.yaml
input_number: !include input_number.yaml
input_boolean: !include input_bool.yaml
input_select: !include input_select.yaml
recorder: !include recorder.yaml
light: !include lights.yaml



lock:
  - platform: mqtt
    name: Backdoor Lock
    state_topic: "smartthings/August - Backdoor/lock"
    command_topic: "smartthings/August - Backdoor/lock"
    payload_lock: "locked"
    payload_unlock: "unlocked"
    state_on: "locked"
    state_off: "unlocked"
    optimistic: false
    retain: true
    
    
