#- platform: plex

- platform: yamaha
  host: 192.168.1.20
  source_ignore:
    - "AUDIO1"
    - "AUDIO2"
    - "AV1"
    - "AV2"
    - "AV3"
    - "AV4"
    - "AV5"
    - "AV6"
    - "Deezer"
    - "HDMI2"
    - "HDMI4"
    - "HDMI5"
    - "NET RADIO"
    - "Pandora"
    - "PHONO"
    - "Rhapsody"
    - "SERVER"
    - "SiriusXM"
    - "TIDAL"
    #- "TUNER"
    - "USB"
    - "V-AUX"
  source_names:
    HDMI1: "PS3"
    HDMI3: "FireStick"
  zone_ignore:
    - "Zone_2"
    #zone_names:
    #  Main_Zone: "Family Room"