- platform: mqtt
  name: "Night Light"
  state_topic: "smartthings/Night Light/switch"
  command_topic: "smartthings/Night Light/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true  

  
#######################################################################################
#                         APEX Controller EB8                                         #
#######################################################################################
- platform: command_line
  switches:
    eb8_outlet1:
      command_on: curl -X POST --user admin:dnkroz_n http://192.168.1.28:7333/status.sht?outlet1_state=2&Update=Update
      command_off: curl -X POST --user admin:dnkroz_n http://192.168.1.28:7333/status.sht?outlet1_state=1&Update=Update
      command_state: curl -u admin:dnkroz_n http://192.168.1.28:7333/cgi-bin/status.xml | grep -i '<name>outlet1</name>' -A2 | grep -E -i 'AO|ON'
      friendly_name: PS3

- platform: command_line
  switches:
    eb8_outlet2:
      command_on: curl -X POST --user admin:dnkroz_n http://192.168.1.28:7333/status.sht?outlet2_state=2&Update=Update
      command_off: curl -X POST --user admin:dnkroz_n http://192.168.1.28:7333/status.sht?outlet2_state=1&Update=Update
      command_state: curl -u admin:dnkroz_n http://192.168.1.28:7333/cgi-bin/status.xml | grep -i '<name>outlet2</name>' -A2 | grep -E -i 'AO|ON'
      friendly_name: FireStick

- platform: command_line
  switches:
    eb8_outlet3:
      command_on: curl -X POST --user admin:dnkroz_n http://192.168.1.28:7333/status.sht?outlet3_state=2&Update=Update
      command_off: curl -X POST --user admin:dnkroz_n http://192.168.1.28:7333/status.sht?outlet3_state=1&Update=Update
      command_state: curl -u admin:dnkroz_n http://192.168.1.28:7333/cgi-bin/status.xml | grep -i '<name>outlet3</name>' -A2 | grep -E -i 'AO|ON'
      #friendly_name: Kitchen Lightswitch
      
- platform: command_line
  switches:
    eb8_outlet4:
      command_on: curl -X POST --user admin:dnkroz_n http://192.168.1.28:7333/status.sht?outlet4_ha_state=2&Update=Update
      command_off: curl -X POST --user admin:dnkroz_n http://192.168.1.28:7333/status.sht?outlet4_ha_state=1&Update=Update
      command_state: curl -u admin:dnkroz_n http://192.168.1.28:7333/cgi-bin/status.xml | grep -i '<name>outlet4_ha</name>' -A2 | grep -E -i 'AO|ON'
      friendly_name: 5Ghz Router
      
- platform: command_line
  switches:
    eb8_outlet5:
      command_on: curl -X POST --user admin:dnkroz_n http://192.168.1.28:7333/status.sht?outlet5_state=2&Update=Update
      command_off: curl -X POST --user admin:dnkroz_n http://192.168.1.28:7333/status.sht?outlet5_state=1&Update=Update
      command_state: curl -u admin:dnkroz_n http://192.168.1.28:7333/cgi-bin/status.xml | grep -i '<name>outlet5</name>' -A2 | grep -E -i 'AO|ON'
      friendly_name: Network Devices
      
- platform: command_line
  switches:
    eb8_outlet6:
      command_on: curl -X POST --user admin:dnkroz_n http://192.168.1.28:7333/status.sht?outlet6_state=2&Update=Update
      command_off: curl -X POST --user admin:dnkroz_n http://192.168.1.28:7333/status.sht?outlet6_state=1&Update=Update
      command_state: curl -u admin:dnkroz_n http://192.168.1.28:7333/cgi-bin/status.xml | grep -i '<name>outlet6</name>' -A2 | grep -E -i 'AO|ON'
      friendly_name: IR Blaster
      
- platform: command_line
  switches:
    eb8_outlet7:
      command_on: curl -X POST --user admin:dnkroz_n http://192.168.1.28:7333/status.sht?outlet7_state=2&Update=Update
      command_off: curl -X POST --user admin:dnkroz_n http://192.168.1.28:7333/status.sht?outlet7_state=1&Update=Update
      command_state: curl -u admin:dnkroz_n http://192.168.1.28:7333/cgi-bin/status.xml | grep -i '<name>outlet7</name>' -A2 | grep -E -i 'AO|ON'
      #friendly_name: Kitchen Lightswitch
      
- platform: command_line
  switches:
    eb8_outlet8:
      command_on: curl -X POST --user admin:dnkroz_n http://192.168.1.28:7333/status.sht?outlet8_ha_state=2&Update=Update
      command_off: curl -X POST --user admin:dnkroz_n http://192.168.1.28:7333/status.sht?outlet8_ha_state=1&Update=Update
      command_state: curl -u admin:dnkroz_n http://192.168.1.28:7333/cgi-bin/status.xml | grep -i '<name>outlet8_ha</name>' -A2 | grep -E -i 'AO|ON'
      friendly_name: Yamaha Receiver
      
#######################################################################################
#  /end                   APEX Controller EB8                                         #
#######################################################################################

#######################################################################################
#                            August Smart Lock                                        #
#######################################################################################
# - platform: mqtt
  # name: Backdoor Lock
  # state_topic: "smartthings/August - Backdoor/lock"
  # command_topic: "smartthings/August - Backdoor/lock"
  # payload_lock: "locked"
  # payload_unlock: "unlocked"
  # state_on: "locked"
  # state_off: "unlocked"
  # optimistic: false
  # retain: true

#######################################################################################
# /end                       August Smart Lock                                        #
#######################################################################################

#######################################################################################
#                                  ROKU                                               #
#######################################################################################
- platform: command_line
  switches:
    tv_power:
      command_on: 'curl -X POST http://192.168.1.125:8060/keypress/PowerOn'
      command_off: 'curl -X POST http://192.168.1.125:8060/keypress/PowerOff'
      command_state: 'curl -s GET http://192.168.1.125:8060/query/device-info | grep power-mode | sed -e "s:<power-mode>DisplayOff</power-mode>:OFF:" -e "s:<power-mode>PowerOn</power-mode>:ON:"'
      value_template: '{{ value == "ON" }}'

#######################################################################################
# /end                             ROKU                                               #
#######################################################################################

- platform: tplink
  name: Dehumidifier
  host: !secret dehumid



