- platform: mqtt
  name: "Night Light"
  state_topic: "smartthings/Night Light/switch"
  command_topic: "smartthings/Night Light/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true  

- platform: mqtt
  name: "Kitchen Table Light"
  state_topic: "smartthings/Kitchen Table/switch"
  command_topic: "smartthings/Kitchen Table/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true