- platform: mqtt
  name: "Full Bath Ceiling Light"
  state_topic: "smartthings/Qubino Flush 2 Relays (Q1)/switch"
  command_topic: "smartthings/Qubino Flush 2 Relays (Q1)/switch"
  payload_on: "on"
  payload_off: "off"
  
- platform: mqtt
  name: "Full Bath Ceiling Fan"
  state_topic: "smartthings/Qubino Flush 2 Relays (Q2)/switch"
  command_topic: "smartthings/Qubino Flush 2 Relays (Q2)/switch"
  payload_on: "on"
  payload_off: "off"