#smartthings/Qubino - Full Bath (Q1)/power
#smartthings/Qubino - Full Bath (Q2)/power
#smartthings/Qubino - Full Bath (Q1)/energy
#smartthings/Qubino - Full Bath (Q2)/energy
#smartthings/Qubino - Full Bath (Q1)/switch
#smartthings/Qubino Flush 2 Relays (Q2)/switch = on



- platform: mqtt
  name: "Full Bath Ceiling Light"
  state_topic: "smartthings/Qubino Flush 2 Relays (Q1)/switch"
  command_topic: "smartthings/Qubino Flush 2 Relays (Q1)/switch"
  payload_on: "on"
  payload_off: "off"
  #optimistic: true
  #retain: true
  
- platform: mqtt
  name: "Full Bath Ceiling Fan"
  state_topic: "smartthings/Qubino Flush 2 Relays (Q2)/switch"
  command_topic: "smartthings/Qubino Flush 2 Relays (Q2)/switch"
  payload_on: "on"
  payload_off: "off"