#
# Sengled Dimable White LED Bulbs 
#
# Zigbee connected to Samsung Smartthings and then replicated via MQTT to HA
#
#

- platform: mqtt
  name: "Back Porch"
  state_topic: "smartthings/Back Porch/switch"
  command_topic: "smartthings/Back Porch/switch"
  brightness_state_topic: "smartthings/Back Porch/level"
  brightness_command_topic: "smartthings/Back Porch/level"
  brightness_scale: 101
  payload_on: "on"
  payload_off: "off"
  optimistic: true
  retain: true
  
- platform: mqtt
  name: "Night Lights"
  state_topic: "smartthings/Bedroom Night Light/switch"
  command_topic: "smartthings/Bedroom Night Light/switch"
  brightness_state_topic: "smartthings/Bedroom Night Light/level"
  brightness_command_topic: "smartthings/Bedroom Night Light/level"
  brightness_scale: 101
  payload_on: "on"
  payload_off: "off"
  optimistic: true
  retain: true