- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - temperature_max
    - temperature
    - humidity
  update_interval: 600
- platform: yr
- platform: time_date
  display_options:
    - 'time'