- platform: waze_travel_time
  name: Home to Downtown
  origin: !secret home
  destination: 1 Energy Plaza, Detroit,MI
  region: 'US'
- platform: waze_travel_time
  name: Home to Work
  origin: !secret home
  destination: !secret work
  region: 'US'
- platform: waze_travel_time
  name: Work to Home
  origin: !secret work
  destination: !secret home
  region: 'US'
- platform: waze_travel_time
  name: Downtown to Home
  origin: '1 Energy Plaza, Detroit, MI'
  destination: !secret home
  region: 'US'
