#
# Technically Switches, but these control lights that can't accept or easily use Hue Bulbs
# 
# Kitchen table is a Edison Bulb Fixture and Spot lights are Halogen Flood/Spot can lights in the kitchen
#
# Connected to Samsung Smartthings and then replicated via MQTT to HA
#

- platform: mqtt
  name: "Kitchen Table Light"
  state_topic: "smartthings/Kitchen Table/switch"
  command_topic: "smartthings/Kitchen Table/switch"
  brightness_state_topic: "smartthings/Kitchen Table/level"
  brightness_command_topic: "smartthings/Kitchen Table/level"
  brightness_scale: 101
  payload_on: "on"
  payload_off: "off"
  optimistic: true
  retain: true
  
- platform: mqtt
  name: "Kitchen Spot Lights"
  state_topic: "smartthings/Kitchen Spot Lights/switch"
  command_topic: "smartthings/Kitchen Spot Lights/switch"
  brightness_state_topic: "smartthings/Kitchen Spot Lights/level"
  brightness_command_topic: "smartthings/Kitchen Spot Lights/level"
  brightness_scale: 101
  payload_on: "on"
  payload_off: "off"
  optimistic: true
  retain: true
    

  
    
